easy_admin:
    design:
        flash_messages:
            create:
                success: 'Nouvel élément créé avec succès.'
                error: 'Une erreur est survenue lors de la création.'
            update:
                success: 'Élément mis à jour avec succès.'
                error: 'Une erreur est survenue lors de la mise à jour.'
            delete:
                success: 'Élément supprimé avec succès.'
                error: 'Une erreur est survenue lors de la suppression.'
            # Ajoutez d'autres actions et messages ici
